### PR TITLE
Admin event detail page

### LINKED ISSUE #20: Admin Event Detail Page Frontend
## Current Event Detail Page:  
image  
image  

## Design:  
image  
image  
image  
image  

## Tasks
- [x] Fill in the missing title and buttons
- [x] Populate the tags field in Event collection
- [ ] Add new endpoint that returns all tags
- [ ] Display tags in the frontend
- [ ] If you have time, make the edit popup window look like the design.

### PR DESCRIPTION
**Pull request by Josephine0110**
Screenshot 2024-01-30 at 11 45 24 PM

On event details page, I added "edit" and "see sign-ups" buttons and the number of spots filled to match with the design.

Screenshot 2024-01-30 at 11 50 04 PM

On the edit page, I added the following:
1. Tags section, which will display the tags of the specific event. It is hard-coded for now.
2. Logistics section, I modified the original time picker to the new one. The admin can now select the date and time at the same time.
Screenshot 2024-01-30 at 11 58 05 PM
3. I made the maximum spots of the event visible on the page
4. I showed the address of the event in the blanks.

### CODE REVIEW

**Comment by intiserp** [comment]
Replaced the styled components with antd components and antd form for better UI and usability. 
1. Performs basic form validation before submitting
2. Submit button greyed out until form is touched
3. Used RangePicker for date selection
4. Connected to backend, changes get saved succesfully
5. Tags fully integrated. [will have to implement feature to create new tags in the feature]
image
image
image

**Comment by intiserp** [comment]
Replaced the styled components with antd components and antd form for better UI and usability. 
1. Performs basic form validation before submitting
1. Used RangePicker for date selection
1. Connected to backend, changes get saved succesfully
1. Added new endpoint to get all tags from db
1. Tags fully integrated [will have to implement feature to create new tags in the feature]
image
image
image

**Comment by intiserp** [comment]
Implemented fetching all the programs and assigning the event to a specific program (frontend and backend). Changing this makes the event show up on the Program management page. 

image

**Review by JiashuHarryHuang — APPROVED** [review]
LGTM

**Pull request merged**
